### ISSUE TITLE
JSX patterns break with no blank line between JS and JSX sections

### ISSUE THREAD

**Issue by levito** [sinnerschrader/patternplate-server#15]
JSX Patterns in the following form break:

```jsx
var a = 1; // no blank line after JS block:
<div>
    test
</div>
```

This also applies to comments before the JSX block.

This works:
```jsx
<div>
    test
</div>
```

This also works:
```jsx
var a = 1; // blank line after JS block:

<div>
    test
</div>
```

**Comment by marionebl** [comment]
https://github.com/sinnerschrader/patternplate-transform-react/commit/f7f7b995390104e9c7313131840b86c81544cbb9

**Comment by marionebl** [comment]
This issue was moved to sinnerschrader/patternplate#42
