### ISSUE TITLE
Allow overriding pattern layout/markup template

### ISSUE THREAD

**Issue by levito** [sinnerschrader/patternplate-server#25]
We should have the possibility to override the default layout (i. e. the markup template, in `application/layouts/index.js`). Currently, it is hardcoded in `application/routes/pattern.js` and `application/tasks/build/index.js`.

This is needed for e. g.:
- having different meta tags
- adding attributes to `html` or `body` elements
- globally adding modernizr

**Comment by marionebl** [comment]
This would also come in handy for simulation of various integration environments, taking this on the roadmap for 0.16.

**Comment by marionebl** [comment]
This issue was moved to sinnerschrader/patternplate#41
