### ISSUE TITLE
Add browserify support for external bundles.

### ISSUE THREAD

**Issue by Palmaswell** [sinnerschrader/patternplate-server#28]
The pattern-plate server browserify transform does not support external bundles.

**Comment by Palmaswell** [comment]
I just made a pull request with the wished functionality. Please give feedback for potential improvements.

**Comment by marionebl** [comment]
Would be amazing if you outlined

* what the use case is
* what API changes this yields 
* what changes on build and demo output this yields

Thanks! :fist:

**Comment by Palmaswell** [comment]
Sure,

1. **Use case**: it is common for projects to have external bundles or dependencies outside of the generated browserify bundle. Most of this cases or constraints are out of the developers reach.
In such cases you don't want to have duplications causing negative side effects to the project. `external` bundles allows you to reference these external files within your application without including them in your bundle. It actually makes absolutely sense to include `ignore` and `exclude` too because this issue is not an isolated  use case, but rather a necessary functionality that a browserify transform  for the patternplate should provide.

2.  **API changes**: well I already made a pull request with an initial draft of how an `external` bundle could look like in the Browserify transform. (Pull Request)[https://github.com/sinnerschrader/patternplate-server/pull/29]. Nevertheless I am even more convinced that `external`, `exclude` and `ignore` bundles should be included. To that we can discuss on my next pull request :)

Currently the `external` bundle is based pretty much on the same implementation of the current transform, speak, within the browserify transforms configuration there is a new  "external" property containing an empty array. The array accepts a string list (paths) of the files to externalize. If the array is empty the transform does nothing,  otherwise `.external()` will be added to the browserify object containing the list of files to externalize. I tested it on the Patternplate too and there was no problem whatsoever to include the list in the Patternplate transforms configuration.

3. **Build & Demo output changes**: this changes are only relevant to the build task and should not be included in Demo. The build output changes are pretty straightforward, the externalized files will not be included the bundle ;)

**Comment by marionebl** [comment]
Ok sounds good, some notes:

* First off: Thanks for bringing this up, it is a glaring omission from browserify-transform
* Left some comments on the changes
* Does this allow for externalization of patterns? In my mind it should. Same goes for ignoring and exclusion
* How does this affect patterns with library JS that do not have any demo?
* I'd rather see `ignore` and `exclude` in the same PR, pseudo code:

```js
function applyBundlerConfig(bundler, method, configs) {
  const fn = bundler[method];
  configs.map(fn);
  return bundler;
}

applyBundlerConfig(bundler, 'external', options.external);
applyBundlerConfig(bundler, 'ignore', options.ignore);
applyBundlerConfig(bundler, 'exclude', options.exclude);
```

**Comment by marionebl** [comment]
Side note: Add yourself to the package.json contributors field as part of this PR ;)

**Comment by marionebl** [comment]
More pseudo code 

```js
['external', 'exclude', 'ignore'].forEach(methodName => applyBundlerConfig(bundler, methodName, options[methodName]));
```

**Comment by Palmaswell** [comment]
Ok cool :)  
I will make the changes and make the pull request as discussed.
Pull request follows soon.

All best

**Comment by Palmaswell** [comment]
The pull request have been updated. Support for the `bundle.external()`,  `bundle.ignore()`, `bundle.exclude()` methods is now available. Appreciate if you take a look at it and give some feedback.

**Comment by marionebl** [comment]
@Palmaswell is this still an issue?
