### ISSUE TITLE
Rendering demos as react components

### ISSUE THREAD

**Issue by KnisterPeter** [sinnerschrader/patternplate-server#30]
A proper mounting of patterns in demos is required for better integration with lifecycle apis.

**Comment by marionebl** [comment]
This needs #45

**Comment by marionebl** [comment]
[x] dev 
[ ] beta
[ ] master

**Comment by marionebl** [comment]
Landed with https://github.com/sinnerschrader/patternplate-server/commit/79c810c9be14dda18ae4489ffaf47a62fcde86da
