### ISSUE TITLE
Using React components from node module fails

### ISSUE THREAD

**Issue by rosczja** [sinnerschrader/patternplate-server#36]
I want to include the react-datepicker component in one of my patterns, 
But it always fails with Invariant validation, render must return a valid React component.

Is this not supported by patternplate?

My index.jsx looks like:

```javascript
import * as React from 'react';
import DatePicker from 'react-datepicker';
import moment from 'moment';

export default class FisDatePicker extends React.Component {

  constructor(props) {
    super(props);
    this.getInitialState = this.getInitialState.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.render = this.render.bind(this);
  }

  getInitialState() {
    return {
      startDate: moment()
    };
  }

  handleChange(date) {
    this.setState({
      startDate: date
    });
  }

  render() {
    return <DatePicker
        onChange={this.handleChange} />;
  }
}
```

**Comment by marionebl** [comment]
Thanks for the report, we'll dig into this.

**Comment by marionebl** [comment]
Hey @rosczja, 

After a short investigation of the issue I collected enough insight to assume this stems from the `react` transform, which rewrites found `import` statements. Not being able to import `node_modules` definitely is undesired behavior and will be fixed shortly, presumably until mid next week. Thanks again for the report!

**Comment by rosczja** [comment]
Hey,

I am not sure this has to do with rewriting import statements. The DatePicker component is imported just fine. If I replace ```<DataPicker...``` with ```React.createElement(DatePicker, {...});``` it works for my FisDatePicker component but now fails in the render method of the DatePicker component.

**Comment by marionebl** [comment]
Hey @rosczja,

so I gave this a whirl (with the exact code provided in the issue) and unfortunately I can not reproduce your specific problem.

Steps:
* `npm install --save react-datepicker@0.13 moment`
* patterns/fis-datepicker/index.jsx
```jsx
import * as React from 'react';
import DatePicker from 'react-datepicker';
import moment from 'moment';

export default class FisDatePicker extends React.Component {

  constructor(props) {
    super(props);
    this.getInitialState = this.getInitialState.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.render = this.render.bind(this);
  }

  getInitialState() {
    return {
      startDate: moment()
    };
  }

  handleChange(date) {
    this.setState({
      startDate: date
    });
  }

  render() {
    return <DatePicker
        onChange={this.handleChange} />;
  }
}
```
* patterns/fis-datepicker/pattern.json
```json
{
  "name": "fis-datepicker",
  "version": "0.1.0"
}
```

This yields the following HTML output:
```html
<div class="datepicker__input-container">
  <input type="text" class="datepicker__input">
</div>
```

Any chance you can provide the console output produced when trying to access your pattern?

Please note that currently the `*.jsx` files are solely capable of producing HTML output - the capability to mount React components in demos will land with issue #30 , alas one of the next feature releases.

**Comment by rosczja** [comment]
Hi,

I used the latest version of the datepicker component. Never thought of using an older one. This has to do with patternplate not supporting react 0.14, right?

I think you can close the issue then.

Thanks.

**Comment by marionebl** [comment]
Hey @rosczja, 

`0.14` support is on the roadmap. I take from your answer `react-datepicker` at `~0.13` works for you then?

Cheers,
Mario
