### ISSUE TITLE
npm start & npm run console scrits are broken on version 0.13.7

### ISSUE THREAD

**Issue by Palmaswell** [sinnerschrader/patternplate-server#38]
With the new version update it is impossible to start the application. 
I realize this matter when I runned a  `npm install` on my **Patternplate** project, at that moment the application was impossible to launch.
When you try to run `npm start` the server throws the following `Error: Cannot find module 'denodeify't`.
The same error is thrown  when you try to build with `npm run console`.

This has major repercussions for all of us using  **Patternplate**.  The quick fix for us was to manually move one version down **0.13.6** on the node_modules directory where the **Patternplate** project resides.

Appreciate your comments.

**Comment by marionebl** [comment]
Hey @Palmaswell, thanks for reporting! Another quickfix would be to install denodeify on your top level project. The error you see presumably originates from the changes on patternplate-server on 0.13.7.

I am pretty aware of this being critical and at the same time I do not have access to a full computer at the moment. 

I'd be more than happy to accept a PR against patternplate-server that adds the missing dependency.

**Comment by marionebl** [comment]
Probably we should deprecate 

- patternplate @0.13.7
- patternplate-server @0.13.7 

As soon as 0.13.8 is ready

**Comment by Palmaswell** [comment]
Hey @marionebl, 
Enjoy your holidays!!!
We can wait for the workaround until the new year!
Now everybody is informed about waht to do until then :)

**Comment by KnisterPeter** [comment]
@marionebl The easiest way would be to remove the 'latest' dist-tag from the npm version 0.13.7.

**Comment by KnisterPeter** [comment]
@Palmaswell @marionebl I've reset the latest tag to 0.13.6
Fresh 'npm install on patternplate' should get the correct version now.
