### ISSUE TITLE
Resolve external NPM imports

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate-server#4]
Currently imports on external NPM components break the module. This is "intended" behaviour (@knisterpeter) and should be resolved in the future.

**Comment by marionebl** [comment]
imports from `node_modules` should work just fine from JS and less files, do you refer to jsx files?

**Comment by KnisterPeter** [comment]
Yes, we are refering to JSX files. The latest update to my pull-request
should handle this.

Mario Nebl <notifications@github.com> schrieb am Fr., 21. Aug. 2015 um
08:13 Uhr:
