### ISSUE TITLE
Transforms[transformName].name is super magic

### ISSUE THREAD

**Issue by meandmax** [sinnerschrader/patternplate-server#48]
The correlation between formats, transform.inFormat, transform.outFormat is not clear and the said config key is

* very specific and undocumented
* case sensitive

This makes writing new transforms near to impossible if you are no core-developer. This needs a better API and documentation rather badly.

**Comment by marionebl** [comment]
The process of adding new transforms is suboptimal in the moment. I am thinking about moving the meta data definitions to the transform definitions by default and letting the user override them via the current config options - this would keep the change non-breaking.

I'll post an example, stay tuned

**Comment by marionebl** [comment]
This issue was moved to sinnerschrader/patternplate#36
