### ISSUE TITLE
Proposal: Separate stateful / stateless components

### ISSUE THREAD

**Issue by ZauberNerd** [sinnerschrader/patternplate-server#53]
Instead of having to create and export a react component class every time,
I would propose to make use of `default` and `named exports`.
So that a stateless component could be written like this (but still be able to use `propTypes` / other static properties):
```javascript
import Input from 'input';

export default (
  <Input className={this.props.className} />
);

export const propTypes = {
  className: React.PropTypes.string
};

export const defaultProps = {
  className: 'foo'
};
```
And for the case where we actually need stateful components we could fall back to using classes (`export default class Input extends React.Component { ... }`).

**Comment by KnisterPeter** [comment]
I would argue against this proposal.
A stateless pattern should be written like this:

`
import Input from 'input';

export SomePattern (
  <Input className={this.props.className} />
);
SomePattern.propTypes = {
  className: React.PropTypes.string
};
SomePattern.defaultProps = {
  className: 'foo'
};

export default SomePattern;
`

This way it is aligned to the react way and there will be no breaking changes if react changes in the future. This is the documented way.

**Comment by ZauberNerd** [comment]
But then `SomePattern` / your default export would need to be a function.
In my proposal you could continue to just write plain jsx (as it is already the case in patternplate - except it also allows you to specify `propTypes` and `defaultProps`).

**Comment by KnisterPeter** [comment]
@ZauberNerd: When patternplate is able to use React 0.14 you there is no need to update it. And regarding to just write JSX: This is not specified by JSX and will be hard to maintain. JSX consists of some expressions (not statements) and are not valid on its own.
I would not recommend to go this way to not get into trouble of creating hard to maintain features for sake of simplicity. This will lead to breaking changes.

A better way would be to create a cli-tool (which is planned) to create a basic pattern template where you could insert your JSX code.

**Comment by KnisterPeter** [comment]
Regarding the current possibility to write plain JSX: This is deprecated in current patternplate
@marionebl

**Comment by KnisterPeter** [comment]
@ZauberNerd Besides the discussion: Writing the three exports you proposed is not much less (or simpler) then to write a function with the PropTypes attached to it.

**Comment by marionebl** [comment]
We'll go down the route where
* The react transform produces stateless components for React >= 0.14 by default without support for "proper" PropTypes and defaultProps when https://github.com/sinnerschrader/patternplate-transform-react/commit/f7f7b995390104e9c7313131840b86c81544cbb9 lands
* When the same change lands you are free to write stateless components - the detection for "plain" jsx files will be positive only for JSX in the outermost scope.
